#!/usr/bin/env bash

grep -o "[0123]*-[0-9]*-[0-9]*T[0-9][0-9]:[0-9][0-9]:[0-9][0-9]" allTexts  | tr 'T' ' ' | ruby -rdate -ne 'p Date.parse($_.chomp).strftime("%y%m")' | tr '"' ' ' | sort | uniq -c | sort -nrk2
